framework: jasmine

postMerge:
  pattern:
    - "spec/**/*[sS]pec.{js,mjs}"

preMerge:
  pattern:
    - "spec/**/*[sS]pec.{js,mjs}"

preRun:
     command:
        - npm install
        - npm run start-server &

smartRun: false

configFile: "spec/support/jasmine.json"

version: 1.0.0